from __future__ import annotations

from typing import Any


def field(key: str, label: str, placeholder: str = "") -> dict[str, str]:
    return {"key": key, "label": label, "placeholder": placeholder}


LARK_WORKFLOW_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "minutes_action_items_to_tasks",
        "title": "妙记待办分配",
        "category": "会议与妙记",
        "description": "读取妙记，提取所有 action items，按负责人创建任务并在群里通知。",
        "prompt": "读一下这个妙记 {{minutes_url}}，帮我把里面所有人提到的 action items 提取出来，按负责人分别创建任务，然后在 {{group_name}} 群里发消息通知到每个人。",
        "fields": [field("minutes_url", "妙记链接"), field("group_name", "群名称")],
    },
    {
        "id": "recommend_group_meeting_times",
        "title": "推荐群会议时间",
        "category": "会议与妙记",
        "description": "为群成员推荐兼顾时区的会议时间，确认后可继续建会并拉群。",
        "prompt": "帮我约 {{group_name}} 里所有人下周开一个小时的同步会，时区都要照顾到，给我推荐 3 个大家都合适的时间选项，我确认后直接建会并拉群。",
        "fields": [field("group_name", "群名称")],
    },
    {
        "id": "minutes_to_doc",
        "title": "妙记转会议纪要",
        "category": "会议与妙记",
        "description": "把妙记整理为会议纪要，并创建飞书文档。",
        "prompt": "读一下这个妙记 {{minutes_url}}，帮我整理成会议纪要，包括主要讨论点、决策事项和 action items，然后创建一个飞书文档，标题用今天的日期加会议名称。",
        "fields": [field("minutes_url", "妙记链接")],
    },
    {
        "id": "weekly_minutes_decision_dashboard",
        "title": "会议决策仪表盘",
        "category": "会议与妙记",
        "description": "汇总上周会议妙记中的决策、待确认问题和 action items 到多维表格并生成仪表盘。",
        "prompt": "读一下我上周所有的会议妙记，把决策类信息、待确认问题、action items 分别提取出来，写入多维表格（三列），然后生成一个简单的仪表盘。",
        "fields": [],
    },
    {
        "id": "book_meeting_room",
        "title": "预订会议室",
        "category": "会议与妙记",
        "description": "按时间、人数和楼层偏好预订会议室，并通知参会人。",
        "prompt": "帮我在 {{date}} 下午2点到3点预订一个可以容纳 {{people_count}} 人的会议室，优先选楼层在 {{floor_preference}} 的，预订好之后发消息通知 {{attendees}}。",
        "fields": [
            field("date", "日期", "例如：明天"),
            field("people_count", "人数", "例如：6"),
            field("floor_preference", "偏好楼层", "例如：15楼以上"),
            field("attendees", "参会人飞书账号列表"),
        ],
    },
    {
        "id": "search_minutes_by_keyword",
        "title": "搜索妙记关键词",
        "category": "会议与妙记",
        "description": "搜索所有妙记，按时间倒序列出相关会议和段落。",
        "prompt": "搜索我的所有妙记，找出讨论过「{{keyword}}」的会议，列出会议名称、日期和相关段落，按时间倒序排列。",
        "fields": [field("keyword", "关键词", "例如：定价策略 / 技术选型 / Q2目标")],
    },
    {
        "id": "meeting_id_to_summary_media",
        "title": "会议ID处理",
        "category": "会议与妙记",
        "description": "从会议 ID 转妙记 token，提取总结待办并下载录音录像。",
        "prompt": "拿到会议ID {{meeting_id}}，帮我：1）转换成妙记token；2）提取会议AI总结和待办事项；3）下载会议录音/录像保存到 {{local_path}}。最后把总结发到 {{group_name}}。",
        "fields": [field("meeting_id", "会议ID"), field("local_path", "本地路径"), field("group_name", "飞书群名称")],
    },
    {
        "id": "send_group_message_as_me",
        "title": "用本人身份发群消息",
        "category": "消息与群组",
        "description": "用当前用户身份向指定群发送消息。",
        "prompt": "给 {{group_name}} 发一条消息：{{message}}。用我自己的身份发送。",
        "fields": [
            field("group_name", "群名称"),
            field("message", "消息内容", "今天下午 3 点我临时有事，之前约的会议推迟一小时，麻烦大家调整一下，抱歉！"),
        ],
    },
    {
        "id": "thread_summary",
        "title": "Thread 摘要",
        "category": "消息与群组",
        "description": "读取完整 Thread 对话链，生成 300 字以内摘要。",
        "prompt": "查看消息 {{message_ref}} 的完整Thread对话链，分析：1）主要讨论了什么问题；2）各方的核心观点是什么；3）是否有达成结论或待办；生成一份300字以内的摘要，发给我。",
        "fields": [field("message_ref", "URL或消息ID")],
    },
    {
        "id": "scan_unread_mentions",
        "title": "未读 @ 消息处理",
        "category": "消息与群组",
        "description": "扫描群未读消息，列出需回复的 @，给重要消息加已读 reaction。",
        "prompt": "扫描我在 {{group_name}} 最近的未读消息：1）所有@我的消息，分析是否需要回复，需要的列出来让我确认；2）对所有需要回应但我还没有Reaction的重要消息加一个👀表情，表示「我已看到」；3）如果群名称已超过90天未更新，提醒我是否需要更新。",
        "fields": [field("group_name", "群名称")],
    },
    {
        "id": "send_direct_message_as_me",
        "title": "用本人身份私聊",
        "category": "消息与群组",
        "description": "按指定语气向联系人发送私聊消息。",
        "prompt": "帮我用我的身份给 {{contact}} 发一条消息：「{{message}}」，注意语气要像我平时说话的风格：{{style}}。",
        "fields": [field("contact", "联系人姓名/飞书账号"), field("message", "消息内容"), field("style", "风格描述", "例如：简洁直接 / 有礼貌 / 用表情")],
    },
    {
        "id": "markdown_to_doc",
        "title": "Markdown 转飞书文档",
        "category": "文档与内容创作",
        "description": "把 Markdown 内容创建为排版良好的飞书文档。",
        "prompt": "把这篇 Markdown 内容创建成飞书文档，排版要好看，标题层级、代码块和表格都要保留，文档名叫 {{title}}。\n\nMarkdown 内容：\n{{markdown_content}}",
        "fields": [field("title", "标题"), field("markdown_content", "Markdown 内容")],
    },
    {
        "id": "review_doc_with_comments",
        "title": "文档审稿评论",
        "category": "文档与内容创作",
        "description": "阅读文档并以评论方式指出清晰度、简洁性问题。",
        "prompt": "{{doc_url}} 阅读一下这篇文档，作为提供给外部用户的说明文档，看是否足够清晰、简洁。不要直接改文档，把你觉得有优化空间的位置划词评论出来，在评论里写上修改意见。",
        "fields": [field("doc_url", "文档链接")],
    },
    {
        "id": "repeated_explanations_to_docs",
        "title": "重复解释转文档",
        "category": "文档与内容创作",
        "description": "从最近妙记中识别重复解释过的主题并整理为标准文档。",
        "prompt": "扫描我最近的妙记，找出我重复解释过 3 次以上的内容，帮我把这些内容整理成标准化文档，每个主题一篇，发布到飞书云文档。",
        "fields": [],
    },
    {
        "id": "search_docs_and_messages",
        "title": "跨文档消息搜索",
        "category": "文档与内容创作",
        "description": "同时搜索云空间、知识库和消息记录，按相关度输出清单。",
        "prompt": "帮我找「{{keyword}}」相关的内容，搜索范围：1）云空间文件和知识库；2）飞书消息记录。整理成清单，包含标题、来源、链接，按相关度排序。",
        "fields": [field("keyword", "关键词", "例如：季度复盘")],
    },
    {
        "id": "create_board_architecture",
        "title": "画板架构图",
        "category": "文档与内容创作",
        "description": "在飞书画板中生成系统架构图。",
        "prompt": "在飞书画板 {{board_url}} 里生成一个系统架构图：包含以下服务节点：{{services}}；连接关系：{{relations}}；使用自动布局，节点加上图标。",
        "fields": [
            field("board_url", "飞书画板URL"),
            field("services", "服务节点", "服务名1、服务名2、服务名3"),
            field("relations", "连接关系", "服务1通过REST API调用服务2，服务2通过消息队列通知服务3"),
        ],
    },
    {
        "id": "share_doc_permissions",
        "title": "文档权限分享",
        "category": "文档与内容创作",
        "description": "搜索人员联系信息并为文档添加查看权限。",
        "prompt": "把文档 {{doc_url}} 的查看权限分享给以下人员：{{people}}，先搜索他们的联系信息，确认后添加权限，完成后告诉我已添加。",
        "fields": [field("doc_url", "文档URL"), field("people", "姓名列表")],
    },
    {
        "id": "doc_image_attachment_ops",
        "title": "文档图片附件处理",
        "category": "文档与内容创作",
        "description": "向文档插入本地图片，并下载文档内所有图片和附件。",
        "prompt": "操作文档 {{doc_url}}：1）把本地图片 {{image_path}} 插入到文档第 {{paragraph_index}} 段之后；2）把文档里所有图片和附件下载到 {{download_dir}}，文件名保持原始名称。",
        "fields": [field("doc_url", "文档URL"), field("image_path", "本地图片路径"), field("paragraph_index", "段落序号"), field("download_dir", "本地文件夹路径")],
    },
    {
        "id": "monitor_doc_comments",
        "title": "文档评论监控",
        "category": "文档与内容创作",
        "description": "监控文档评论动态，处理 @ 评论、reaction 和超时提醒。",
        "prompt": "监控文档 {{doc_url}} 的评论动态：1）有新的@{{my_name}}评论时，分析问题并回复；2）我自己的回复收到Reaction时，记录下来说明对方已阅；3）超过24小时未回复的评论，提醒我处理。",
        "fields": [field("doc_url", "文档URL"), field("my_name", "我的名字")],
    },
    {
        "id": "create_lark_slides",
        "title": "生成飞书 Slides",
        "category": "文档与内容创作",
        "description": "根据大纲生成飞书 Slides 演示文稿。",
        "prompt": "帮我根据以下大纲生成一份飞书Slides演示文稿：标题「{{title}}」，共 {{page_count}} 页：{{outline}}。生成后发链接给我。",
        "fields": [field("title", "演示标题"), field("page_count", "页数"), field("outline", "逐页大纲")],
    },
    {
        "id": "draft_followup_email_with_images",
        "title": "含图跟进邮件草稿",
        "category": "邮件管理",
        "description": "生成正式跟进邮件并附上本地截图，发送前确认。",
        "prompt": "帮我给 {{recipient}} 写一封跟进邮件，附上这两张截图 {{image_path_1}} {{image_path_2}}，邮件风格正式，主题是 {{subject}}，写好后让我确认再发。",
        "fields": [field("recipient", "收件人姓名/邮箱"), field("image_path_1", "截图路径1"), field("image_path_2", "截图路径2"), field("subject", "邮件主题")],
    },
    {
        "id": "unread_email_triage",
        "title": "未读邮件分类",
        "category": "邮件管理",
        "description": "分类未读邮件，将重要摘要推群并生成草稿回复。",
        "prompt": "查看我所有的未读邮件，重要邮件（需要我回复或决策的）发摘要到 {{group_name}}，并给每封邮件写一个草稿回复。",
        "fields": [field("group_name", "项目群名称")],
    },
    {
        "id": "send_email_with_recall_window",
        "title": "邮件确认与撤回窗口",
        "category": "邮件管理",
        "description": "发送前展示草稿，发送后保留 30 秒撤回窗口。",
        "prompt": "帮我给 {{recipient}} 发一封邮件，主题：{{subject}}，内容：{{content}}。发送前先给我看一下草稿确认，发出去之后如果我在30秒内说「撤回」，立刻帮我撤销这封邮件。",
        "fields": [field("recipient", "收件人"), field("subject", "主题"), field("content", "内容")],
    },
    {
        "id": "monitor_new_emails",
        "title": "新邮件监听处理",
        "category": "邮件管理",
        "description": "实时监听新邮件，分类并为需要处理的邮件生成建议。",
        "prompt": "帮我处理邮件：1）实时监听新邮件到达；2）有新邮件时快速扫描主题和摘要，分类为「需要我处理」/「仅供参考」/「可忽略」；3）「需要我处理」的读取完整Thread对话历史，生成处理建议，推送到 {{group_name}}。",
        "fields": [field("group_name", "飞书群名称")],
    },
    {
        "id": "business_email_with_signature",
        "title": "商务邮件带签名",
        "category": "邮件管理",
        "description": "按大纲生成商务邮件并自动附上签名。",
        "prompt": "帮我给 {{recipient}} 发一封商务邮件，主题「{{subject}}」，内容：{{outline}}，自动附上我的邮件签名，签名格式：{{signature}}。",
        "fields": [field("recipient", "收件人"), field("subject", "主题"), field("outline", "内容大纲"), field("signature", "签名格式", "姓名/职位/公司/联系方式")],
    },
    {
        "id": "today_calendar_task_plan",
        "title": "今日日历任务重点",
        "category": "任务与计划",
        "description": "根据今天的日历和未完成任务生成重点清单。",
        "prompt": "帮我看一下今天的日历和所有未完成任务，整理一份今日重点清单，按优先级排列，标出哪些有时间截止。",
        "fields": [],
    },
    {
        "id": "today_due_task_summary",
        "title": "今日到期任务汇总",
        "category": "任务与计划",
        "description": "查询与我相关、今天到期或已逾期的任务并排序。",
        "prompt": "帮我汇总今天需要处理的任务：1）查询「和我相关的所有任务」（我创建的+我负责的+指派给我的）；2）筛选出截止日期是今天或已逾期的；3）按优先级排序，生成一份今日计划清单发给我。",
        "fields": [],
    },
    {
        "id": "add_subtasks_comment_reminder",
        "title": "任务子任务评论提醒",
        "category": "任务与计划",
        "description": "为任务添加子任务、评论和截止前提醒。",
        "prompt": "在任务「{{task_name}}」下：1）创建3个子任务：{{subtasks}}；2）添加评论「{{comment}}」；3）设置提醒：截止前1天提醒我；完成后把任务链接发给我。",
        "fields": [field("task_name", "任务名称"), field("subtasks", "子任务列表", "子任务1、子任务2、子任务3"), field("comment", "备注内容")],
    },
    {
        "id": "create_project_task_tree",
        "title": "项目任务树",
        "category": "任务与计划",
        "description": "创建主任务、子任务负责人、截止时间和提醒。",
        "prompt": "帮我在飞书任务里创建以下任务结构：主任务「{{project_name}}」截止 {{deadline}}，子任务：{{subtask_plan}}；每个子任务都开启截止前1天提醒。",
        "fields": [field("project_name", "项目名称"), field("deadline", "主任务截止日期"), field("subtask_plan", "子任务负责人和日期", "子任务1 负责人张三 截止日期；子任务2 负责人李四 截止日期")],
    },
    {
        "id": "subscribe_task_events",
        "title": "订阅任务事件",
        "category": "任务与计划",
        "description": "订阅新任务指派和任务状态变更提醒。",
        "prompt": "帮我订阅飞书任务事件：1）有新任务指派给我时，立即分析任务内容，判断优先级（紧急/普通），发消息提醒我：「新任务：【任务名】，截止【日期】，建议优先级：【高/中/低】」；2）我负责的任务有人修改完成状态时，告知我变更内容。",
        "fields": [],
    },
    {
        "id": "sheet_find_rows_analyze",
        "title": "表格查数分析",
        "category": "多维表格与电子表格",
        "description": "在表格中查找关键行，列字段并计算总额和平均值。",
        "prompt": "在表格 {{sheet_url}} 里帮我找 {{keyword}} 相关的所有行，列出它们的 {{fields}}，并计算总金额和平均值。",
        "fields": [field("sheet_url", "表格URL"), field("keyword", "客户名/关键词"), field("fields", "字段名", "例如：合同金额、状态、联系人")],
    },
    {
        "id": "base_form_automation",
        "title": "Base 表单自动化",
        "category": "多维表格与电子表格",
        "description": "为 Base 表单配置提交和状态流转通知。",
        "prompt": "查看 {{base_name}} 里的表单，帮我为新提交的记录配置自动化流程：1）新提交 → 发消息给 {{owner}}；2）状态改为「处理中」 → 通知提交人；3）状态改为「已完成」 → 发确认消息并关闭记录。",
        "fields": [field("base_name", "Base名称"), field("owner", "负责人飞书账号")],
    },
    {
        "id": "base_upload_attachment",
        "title": "Base 上传附件",
        "category": "多维表格与电子表格",
        "description": "定位 Base 记录并上传本地文件到附件字段。",
        "prompt": "在Base {{base_url}} 的 {{table_name}} 表里，找到 {{filter}} 的记录，把本地文件 {{file_path}} 上传到「附件」字段中。",
        "fields": [field("base_url", "Base URL"), field("table_name", "表名"), field("filter", "字段值", "例如：客户名=XXX公司"), field("file_path", "本地文件路径")],
    },
    {
        "id": "base_role_permissions",
        "title": "Base 角色权限",
        "category": "多维表格与电子表格",
        "description": "配置 Base 角色权限并分配人员。",
        "prompt": "在Base {{base_url}} 里帮我配置权限：1）创建「销售团队」角色，能查看「客户信息」表但不能编辑；2）创建「运营团队」角色，能编辑「活动数据」表；3）把以下人员分配到对应角色：{{assignments}}。",
        "fields": [field("base_url", "Base URL"), field("assignments", "姓名到角色映射列表")],
    },
    {
        "id": "archive_group_files_to_drive",
        "title": "群文件整理到云盘",
        "category": "云盘与知识库",
        "description": "下载群内图片和文件，按类型上传到云盘文件夹。",
        "prompt": "扫描 {{group_name}} 最近7天的消息，把所有图片和文件下载下来，按以下规则上传到云盘 {{folder_url}}：图片归到「图片」文件夹，文档归到「文档」文件夹，完成后发消息给我确认。",
        "fields": [field("group_name", "群名称"), field("folder_url", "云盘文件夹URL")],
    },
    {
        "id": "drive_large_file_cleanup",
        "title": "云盘大文件整理",
        "category": "云盘与知识库",
        "description": "上传大文件、导出 PPTX 为 PDF 并移动旧文件夹内容。",
        "prompt": "帮我整理云盘 {{folder_url}}：1）把本地 {{file_path}} 的大文件上传进去（自动分片）；2）把云盘里所有.pptx文件导出为PDF并下载到 {{download_path}}；3）把 {{old_folder_url}} 里的文件移动到这个文件夹。",
        "fields": [field("folder_url", "目标文件夹URL"), field("file_path", "本地文件路径"), field("download_path", "本地下载路径"), field("old_folder_url", "旧文件夹URL")],
    },
    {
        "id": "wiki_manage_nodes",
        "title": "知识库节点管理",
        "category": "云盘与知识库",
        "description": "列知识库层级、移动文档并创建子文档。",
        "prompt": "帮我管理知识库 {{wiki_url}}：1）列出所有一级节点和子节点的层级结构；2）把文档 {{doc_url}} 移动到「{{target_node}}」下；3）为「{{parent_node}}」创建一个新的子文档，标题是「{{title}}」。",
        "fields": [field("wiki_url", "Wiki URL"), field("doc_url", "文档URL"), field("target_node", "目标节点名称"), field("parent_node", "新子文档父节点"), field("title", "标题")],
    },
    {
        "id": "approval_batch_handle",
        "title": "审批批量处理",
        "category": "自动化与审批",
        "description": "按金额规则自动同意部分审批，其余列出等待确认。",
        "prompt": "查询我当前所有待审批任务，按以下规则处理：1）金额在 {{threshold}} 以下的报销申请直接同意；2）其余逐条列出，包括申请人、事由、金额，等我确认后再批；3）超过3天未处理的列出提醒我。",
        "fields": [field("threshold", "阈值", "例如：1000元")],
    },
    {
        "id": "subscribe_lark_events",
        "title": "订阅飞书事件",
        "category": "自动化与审批",
        "description": "订阅消息、审批和任务事件，并按规则自动处理。",
        "prompt": "帮我订阅以下飞书事件，并按规则自动处理：1）{{group_name}} 有新消息@我 → 分析后决定是否需要我立即回复，如是则提醒我；2）有新审批请求 → 属于费用报销类且金额<500直接批；3）有人给我分配了任务 → 自动加到今天的计划清单。",
        "fields": [field("group_name", "群名称")],
    },
    {
        "id": "approval_status_followup",
        "title": "审批状态跟进",
        "category": "自动化与审批",
        "description": "查询我提交的审批状态，超时则友好提醒当前审批人。",
        "prompt": "查询我提交的 {{approval_type}} 申请的最新状态，如果超过 {{days}} 天未处理，查出当前负责审批的人是谁，发消息给他「提醒」一下，消息要友好不要显得催促。",
        "fields": [field("approval_type", "审批类型", "例如：报销 / 请假"), field("days", "天数", "例如：2")],
    },
    {
        "id": "recommend_skills_from_activity",
        "title": "活动推荐 Skills",
        "category": "AI 记忆与 Skills",
        "description": "根据最近飞书活动推荐适合的 skills 或封装重复流程。",
        "prompt": "看看我最近一周在飞书上的活动（群聊、文档、日历、妙记），帮我推荐一些适合我的 skills，或者帮我把我经常重复做的事情封装成 skill。",
        "fields": [],
    },
    {
        "id": "update_memory_from_activity",
        "title": "活动更新记忆",
        "category": "AI 记忆与 Skills",
        "description": "从飞书活动中更新协作网络、工作重点和决策偏好记忆。",
        "prompt": "扫描我最近一周的飞书活动（妙记、群聊、文档、日历），更新你对我的记忆，包括我的协作网络、工作重点、决策偏好等，写进你的 memory 文件。",
        "fields": [],
    },
    {
        "id": "create_lark_skill",
        "title": "创建飞书 Skill",
        "category": "AI 记忆与 Skills",
        "description": "创建一个可复用的飞书 Skill。",
        "prompt": "帮我创建一个飞书Skill，名字叫「{{skill_name}}」，功能描述：{{description}}。把这个Skill发给我，让我以后直接引用。",
        "fields": [field("skill_name", "Skill名称", "例如：周报生成器"), field("description", "功能说明")],
    },
    {
        "id": "openapi_explorer_call",
        "title": "OpenAPI Explorer 调试",
        "category": "进阶与开发者",
        "description": "查找飞书接口并调用指定接口查看返回。",
        "prompt": "帮我用OpenAPI Explorer查找飞书里关于「{{keyword}}」的接口，列出相关接口名称和说明，然后帮我调用 {{api_name}}，参数：{{params}}，看看返回什么。",
        "fields": [field("keyword", "功能关键词", "例如：会议室 / 邮件 / 审批"), field("api_name", "接口名"), field("params", "参数")],
    },
    {
        "id": "query_resource_fields_table",
        "title": "资源字段查询",
        "category": "进阶与开发者",
        "description": "查询飞书资源并只返回指定字段，以表格展示。",
        "prompt": "查询 {{resource}}，只返回其中的 {{fields}} 字段，用表格格式展示结果。",
        "fields": [field("resource", "飞书资源", "例如：群列表 / 日历事件 / 任务清单"), field("fields", "字段名", "例如：name/id/owner")],
    },
]
